build:
  version: "1.4.0"
dailytech:
  message: "Welcome to DAILYTECH-CONFIG"
  contactDetails:
    name: "Thomas Maesatas - Developer"
    email: "thomas1.maestas@gmail.com"
  dependsOn:
    - NONE
  depenedencies:
    - DAILYTECH-AUTH
    - DAILYTECH-REST
    - DAILYTECH-REST
    - ORGANIZATION-SERVICE
####################################################
server.address: 0.0.0.0
spring.application.name: DAILYTECH-CONFIG
application.version: 1.4.0
server.port: 8888
spring.profiles.active: native # git  #

eureka.instance.client.serverUrl.defaultZone: http://localhost:8761/eureka/
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true

##### Config   Versus GITHUB or LOCAL / FILESYSTEM (native) #####
#spring.profiles.active: git
#spring.profiles.active: native

spring.cloud.config.server.native.search-locations: classpath:/config

#spring.cloud.config.server.git.uri: https://github.com/thomasm1/config-server-repo
#spring.cloud.config.server.git.default-label: main

##spring.cloud.config.server.native.search-locations: file:///C://config
##### END Config LOCAL Versus GITHUB


spring.cloud.config.server.git.clone-on-start: true

##  info + actuator + data-rest + zipkin-tracing + swagger endpoints
spring.data.rest.base-path: /rest/
info.app.name: ${spring.application.name}
info.app.description: ${spring.application.name} Server Application
info.app.version: ${spring.application.version}
info.app.is-cloud: ${spring.cloud.config.enabled:false}
info.app.config: ${spring.profiles.active}-${spring.cloud.config.server.native.search-locations}
#   actuator
management.info.env.enabled: true
management.endpoint.health.show-details: always #health,metrics
management.endpoints.web.exposure.include: "*"
#  zipkin-tracing
spring.zipkin.base-url: http://127.0.0.1:9411/
spring.sleuth.sampler.probability: 1.0
# Log
logging.level.ROOT:  INFO
logging.level.org.spring.framework.cloud.config:  DEBUG


#encrypt.key: mapl