apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app:  dailytech-config
  name: dailytech-config
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dailytech-config
  type: ClusterIP
status:
  loadBalancer: {}

#  1 kubectl create service clusterip dailytech-config --tcp=8080:8080 --dry-run=client -o=yaml >> service.yml
#  2. kubectl apply -f service.yml
#  3. service.yml

